---

# Creates a target group for the application load balancer

  - name: Create the target group for the load balancer
    community.aws.elb_target_group:
      name: '{{ tg_name }}'
      protocol: http
      port: 80
      vpc_id: '{{ vpc_id }}'
      health_check_protocol: http
      health_check_path: /
      successful_response_codes: "200,250-260"
      targets:
        - Id: '{{ asg_instance_id[0] }}'
          Port: 80
        - Id: '{{ asg_instance_id[1] }}'
          Port: 80
      state: present
      region: '{{ aws_region }}'
    register: tg
    tags:
      - SG
      - tg
  - name: store the target group name
    set_fact:
      tg_group_name: '{{ tg.target_group_name }}'
      tg_group_arn: '{{ tg.target_group_arn }}'
      cacheable: yes
