---
# Create an autoscaling group in the private subnets using the launch template

  - name: Create autoscaling group
    community.aws.ec2_asg:
      name: '{{ asg_name }}'
      availability_zones: [ '{{ az_01 }}', '{{ az_02 }}' ]
      launch_template:
        launch_template_id: "{{ launch_temp_id }}"
      min_size: 2
      max_size: 5
      desired_capacity: 2
      vpc_zone_identifier: [ '{{ priv_01_subnet_id }}', '{{ priv_02_subnet_id }}' ]
      health_check_type: ELB
      health_check_period: 120
      wait_for_instances: true
      region: '{{ aws_region }}'
    register: autosg
    tags:
      - SG
      - autosg

  - name: store the instance id
    set_fact:
      asg_instance_id: '{{ autosg.instances }}'
    tags:
      - autosg
      - SG

